import { and, eq } from 'drizzle-orm';
import type { Database } from '@/lib/db/connection';
import { dailyPuzzles, solveAttempts, type DailyPuzzle } from '@/lib/db/schema';
import {
  DAILY_BOARDS,
  toDailyPuzzleRow,
  type DailyDifficulty,
} from '@/lib/db/daily-row';
import { generateSudoku, type Difficulty } from '@/features/engine/sudoku';
import { generateKillerSudoku, type KillerDifficulty } from '@/features/engine/killer/killer-sudoku';
import { BOT_USER_ID, ensureBotUser } from '@/features/leaderboards/bot';

/**
 * Daily-puzzle data access. Every function takes the Drizzle `db` as its first
 * argument rather than importing the `server-only` client at module scope — that keeps
 * this module importable from BOTH the API routes (which pass the guarded app client)
 * and the standalone seed script (which runs under `tsx`, where the guard would throw).
 * The `Database` import is type-only, so nothing here pulls the Neon driver at import.
 *
 * All access is parameterized through Drizzle (AGENTS.md §6). Ownership/authorization is
 * not a concern here — daily puzzles are shared, public, and read-only to clients; the
 * BOLA-sensitive writes live in the leaderboard/solve service (4.3.1 / 4.4).
 */

export interface GenerateDailiesResult {
  isoDate: string;
  requested: number;
  inserted: number;
}

/**
 * Generate and persist one puzzle per eligible difficulty for `isoDate` (UTC).
 * Idempotent: the `UNIQUE(date, difficulty)` constraint plus `onConflictDoNothing` make
 * a re-run a no-op, so the cron is safe to retry and a same-day second call inserts 0.
 */
export async function generateDailyPuzzles(
  db: Database,
  isoDate: string,
): Promise<GenerateDailiesResult> {
  await ensureBotUser(db);

  // One row per registry board: three sections (classic 9×9, the full Killer ladder, minis).
  // The heavy hitters are classic extreme (digger) and killer-extreme (~5.5 s tier-5 search);
  // everything else is milliseconds — the cron route carries maxDuration headroom for the sum.
  const rows = DAILY_BOARDS.map((board) =>
    toDailyPuzzleRow(
      board.variant === 'killer'
        ? generateKillerSudoku(board.difficulty as KillerDifficulty, { gridSize: board.gridSize as 6 | 9 })
        : generateSudoku(board.difficulty as Difficulty, board.gridSize),
      isoDate,
      board.key,
    ),
  );

  const inserted = await db
    .insert(dailyPuzzles)
    .values(rows)
    .onConflictDoNothing({ target: [dailyPuzzles.date, dailyPuzzles.difficulty] })
    .returning({ id: dailyPuzzles.id });

  await seedBotSolves(db, isoDate);

  return { isoDate, requested: rows.length, inserted: inserted.length };
}

/**
 * Give "Sudoku Bot" (`features/leaderboards/bot.ts`) a clean, good-but-beatable solve on
 * every one of today's boards — a visible "time to beat" while the real player base is
 * small. Runs a fresh SELECT of today's rows (not the insert's `.returning()`, which only
 * covers rows inserted THIS call) so it also backfills boards generated by an earlier run
 * before this feature existed. Idempotent via the same `(user, puzzle)` unique index real
 * players' attempts already enforce.
 */
async function seedBotSolves(db: Database, isoDate: string): Promise<void> {
  const todaysPuzzles = await db
    .select({ id: dailyPuzzles.id, key: dailyPuzzles.difficulty })
    .from(dailyPuzzles)
    .where(eq(dailyPuzzles.date, isoDate));

  const botTimeByKey = new Map(DAILY_BOARDS.map((board) => [board.key as string, board.botTimeMs]));
  const attempts = todaysPuzzles
    .filter((p) => botTimeByKey.has(p.key))
    .map((p) => ({
      userId: BOT_USER_ID,
      puzzleId: p.id,
      timeMs: botTimeByKey.get(p.key)!,
      completed: true,
      mistakes: 0,
    }));

  if (attempts.length === 0) return;

  await db
    .insert(solveAttempts)
    .values(attempts)
    .onConflictDoNothing({ target: [solveAttempts.userId, solveAttempts.puzzleId] });
}

/**
 * Fetch the single daily puzzle for a given UTC date + difficulty, or `null` if the
 * cron has not generated it yet. Returns the full row including `solution`; the CALLER
 * (the route) decides what to expose to the client.
 */
export async function getDailyPuzzle(
  db: Database,
  isoDate: string,
  difficulty: DailyDifficulty,
): Promise<DailyPuzzle | null> {
  const [row] = await db
    .select()
    .from(dailyPuzzles)
    .where(and(eq(dailyPuzzles.date, isoDate), eq(dailyPuzzles.difficulty, difficulty)))
    .limit(1);

  return row ?? null;
}
